### ISSUE TITLE
Collaborate with the community effort

### ISSUE THREAD

**Issue by Potherca** [Yubico/yubico-php-client#1]
Currently the [enygma/yubikey](https://github.com/enygma/yubikey) package by Chris Cornutt is the defacto standard [package on Packagist for working with the YubiKey API](https://packagist.org/search/?q=yubikey). Instead of creating a double effort, it might be useful to either 
- [contact Chris](https://twitter.com/enygma) to colaborate on code in his repo (or you guys could just send PRs over there) or
- If you guys want to have more control over the code, clone his repo (or copy/paste/adapt/credit) and integrate improvements yourselves.

If the code moves over to your corner of github, Chris might also be a willing to create more exposure for your lib, as "supported by the original vendor" is usually preferable to "created by the community" alone.

Assuming the quality of the code will be up to par, I'm pretty sure that Chris won't mind if you guys do all the work saving him time he would otherwise have to spend maintaining that code (and any issues or future changes that may arise from the API being improved). :smile:

**Comment by minisu** [comment]
I just added enygma/yubikey to https://developers.yubico.com/OTP/Libraries/List_of_libraries.html[this page], which is where we list known good libs.
